import { NextResponse } from 'next/server';
import { apiError, getSupabaseAdmin, requireAdmin, requireUser } from '@/lib/server/auth';
import { orIlike } from '@/lib/server/query';

export const dynamic = 'force-dynamic';

function category(entity: string) { const value = entity.toLowerCase(); if (value.includes('leave')) return 'Leave'; if (value.includes('payroll')) return 'Payroll'; if (value.includes('document')) return 'Documents'; if (value.includes('expense')) return 'Expenses'; if (value.includes('auth')) return 'Authentication'; if (value.includes('report')) return 'Reports'; if (value.includes('system')) return 'System'; return 'Employee'; }
function normalize(row: any) { const actor = Array.isArray(row.user) ? row.user[0] : row.user; const action = String(row.action ?? '').replace(/_/g, ' '); const label = action.replace(/\b\w/g, (c: string) => c.toUpperCase()); const target = row.entity_type ? `${row.entity_type.replace(/_/g, ' ')}${row.entity_id ? ` · ${row.entity_id}` : ''}` : 'System'; return { id: row.id, actor: actor?.email ?? 'System', initials: (actor?.email ?? 'SY').slice(0, 2).toUpperCase(), action: label, target, category: category(row.entity_type ?? ''), time: new Date(row.created_at).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short' }), date: new Date(row.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }), dateISO: row.created_at.slice(0, 10), ip: row.ip_address ?? 'Internal', detail: row.new_value ?? row.old_value ?? `${label} recorded`, before: null, after: null }; }
export async function GET(request: Request) { try { const user = await requireUser(request); requireAdmin(user); const { searchParams } = new URL(request.url); const search = searchParams.get('search')?.trim(); const categoryFilter = searchParams.get('category'); const from = searchParams.get('from'); const to = searchParams.get('to'); const page = Math.max(1, Number(searchParams.get('page') ?? 1)); const perPage = Math.min(100, Math.max(1, Number(searchParams.get('per_page') ?? 50))); const client = getSupabaseAdmin(); let query = client.from('audit_logs').select('*, user:user_id(email)', { count: 'exact' }).eq('organization_id', user.organization_id); if (search) query = query.or(orIlike(search, ['entity_type', 'action', 'new_value'])); if (from) query = query.gte('created_at', from); if (to) query = query.lt('created_at', `${to}T23:59:59.999Z`); const start = (page - 1) * perPage; const { data, count, error } = await query.order('created_at', { ascending: false }).range(start, start + perPage - 1); if (error) throw error; const items = (data ?? []).map(normalize).filter((row: any) => !categoryFilter || categoryFilter === 'All activity' || row.category === categoryFilter); return NextResponse.json({ items, total: count ?? 0, page, per_page: perPage, total_pages: Math.max(1, Math.ceil((count ?? 0) / perPage)) }); } catch (error) { return apiError(error); } }
