'use client';

import { useMemo, useState } from 'react';
import { Users, ChevronDown, GitBranch, UserRound, ZoomIn, ZoomOut, Maximize2, Search, X, ChevronRight } from 'lucide-react';
import ModuleHeader from '@/components/ui/ModuleHeader';
import EmptyState from '@/components/ui/EmptyState';
import { useToast } from '@/components/ui/Toast';

type Team = { name: string; lead: string; initials: string; count: number; color: string; children?: string[]; description: string };

const teams: Team[] = [
  { name: 'Human Resources', lead: 'Rina Sari', initials: 'RS', count: 24, color: 'bg-primary-surface text-primary', description: 'People, culture, and workplace operations' },
  { name: 'Engineering', lead: 'Budi Hartono', initials: 'BH', count: 186, color: 'bg-cta-surface text-cta-hover', children: ['Platform Engineering', 'Mobile Engineering', 'Web Engineering'], description: 'Product technology and infrastructure' },
  { name: 'Product & Design', lead: 'Maya Anggraeni', initials: 'MA', count: 48, color: 'bg-violet-50 text-violet-600', description: 'Product strategy, research, and design' },
  { name: 'Finance', lead: 'Andi Pratama', initials: 'AP', count: 32, color: 'bg-amber-50 text-accent-yellow', description: 'Financial planning and accounting' },
  { name: 'Marketing', lead: 'Sari Dewi', initials: 'SD', count: 56, color: 'bg-pink-50 text-pink-600', description: 'Brand, growth, and communications' },
  { name: 'Customer Success', lead: 'Yuni Kartika', initials: 'YK', count: 94, color: 'bg-sky-50 text-sky-600', description: 'Customer experience and support' },
];

export default function OrgChartPage() {
  const [expanded, setExpanded] = useState<string[]>(['Engineering']);
  const [zoom, setZoom] = useState(1);
  const [search, setSearch] = useState('');
  const [selectedTeam, setSelectedTeam] = useState<Team | null>(null);
  const { toast } = useToast();
  const filtered = useMemo(() => teams.filter((team) => `${team.name} ${team.lead}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const expandAll = () => { setExpanded(teams.filter((team) => team.children).map((team) => team.name)); toast('All nested teams expanded.', 'info'); };
  const collapseAll = () => { setExpanded([]); toast('Nested teams collapsed.', 'info'); };
  const toggle = (name: string) => setExpanded((current) => current.includes(name) ? current.filter((item) => item !== name) : [...current, name]);

  return <div>
    <ModuleHeader eyebrow="Organization" title="Organization Chart" description="See reporting lines and team structure at a glance" action={<div className="flex gap-2"><button onClick={expanded.length ? collapseAll : expandAll} className="btn-secondary gap-2"><GitBranch size={15} /> {expanded.length ? 'Collapse all' : 'Expand all'}</button></div>} />
    <div className="card mb-6 overflow-hidden">
      <div className="px-5 py-4 border-b border-hairline-soft flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-bold text-ink">Company structure</h2><p className="text-xs text-muted mt-1">Click a team to view details</p></div><div className="flex items-center gap-2"><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-soft" /><input value={search} onChange={(event) => setSearch(event.target.value)} aria-label="Search organization chart" placeholder="Search team or lead…" className="w-48 min-h-10 rounded-pill bg-surface-strong pl-8 pr-3 py-2 text-xs text-ink focus:outline-none focus:ring-2 focus:ring-primary/20" /></div><button onClick={() => setZoom((value) => Math.max(0.75, Number((value - 0.1).toFixed(1))))} aria-label="Zoom out" className="min-h-10 min-w-10 rounded-lg bg-surface-strong hover:bg-primary-surface flex items-center justify-center"><ZoomOut size={15} className="text-muted" /></button><span className="text-xs font-mono text-muted w-10 text-center">{Math.round(zoom * 100)}%</span><button onClick={() => setZoom((value) => Math.min(1.25, Number((value + 0.1).toFixed(1))))} aria-label="Zoom in" className="min-h-10 min-w-10 rounded-lg bg-surface-strong hover:bg-primary-surface flex items-center justify-center"><ZoomIn size={15} className="text-muted" /></button><button onClick={() => setZoom(1)} aria-label="Reset zoom" className="min-h-10 min-w-10 rounded-lg bg-surface-strong hover:bg-primary-surface flex items-center justify-center"><Maximize2 size={15} className="text-muted" /></button></div></div>
      <div className="overflow-x-auto"><div className="min-w-[950px] py-8 transition-transform origin-top" style={{ transform: `scale(${zoom})`, marginBottom: `${(zoom - 1) * 280}px` }}><div className="flex flex-col items-center"><div className="rounded-xl border-2 border-primary bg-primary-surface px-7 py-4 text-center shadow-card"><div className="mx-auto mb-2 flex h-11 w-11 items-center justify-center rounded-full bg-primary text-white"><UserRound size={20} /></div><p className="text-sm font-bold text-ink">Arif Darmawan</p><p className="mt-1 text-xs text-primary">Chief Executive Officer</p></div><div className="h-8 w-px bg-primary-light" /><div className="relative h-px w-[850px] bg-primary-light"><span className="absolute left-1/2 top-0 h-5 w-px bg-primary-light" /></div>{filtered.length === 0 ? <div className="pt-8"><EmptyState title="No teams found" description="Try another search term." /></div> : <div className="grid grid-cols-6 gap-3 pt-5">{filtered.map((team) => <div key={team.name} className="relative flex flex-col items-center"><div className="absolute -top-5 h-5 w-px bg-primary-light" /><button onClick={() => setSelectedTeam(team)} className="w-[135px] rounded-xl border border-hairline bg-canvas p-3 text-center hover:border-primary-light hover:shadow-card-hover transition-all cursor-pointer"><div className={`mx-auto mb-2 flex h-9 w-9 items-center justify-center rounded-full ${team.color}`}><span className="text-xs font-bold">{team.initials}</span></div><p className="truncate text-xs font-bold text-ink">{team.name}</p><p className="mt-1 truncate text-[10px] text-muted">{team.lead}</p><div className="mt-2 inline-flex items-center gap-1 rounded-pill bg-surface-strong px-2 py-1 text-[10px] font-semibold text-body"><Users size={10} /> {team.count}</div></button>{team.children && <button onClick={() => toggle(team.name)} className="mt-2 inline-flex min-h-8 items-center gap-1 rounded-pill bg-primary-surface px-2.5 text-[10px] font-semibold text-primary hover:bg-primary-light/20"><ChevronDown size={11} className={`transition-transform ${expanded.includes(team.name) ? '' : '-rotate-90'}`} />{expanded.includes(team.name) ? 'Hide sub-teams' : `${team.children.length} sub-teams`}</button>}{team.children && expanded.includes(team.name) && <div className="mt-2 flex flex-col items-center gap-1">{team.children.map((child) => <div key={child} className="w-[135px] rounded-lg border border-dashed border-hairline px-2 py-2 text-center text-[10px] font-semibold text-muted"><ChevronDown size={11} className="mx-auto mb-0.5 text-primary" />{child}</div>)}</div>}</div>)}</div>}</div></div></div>
    </div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-5"><div className="card"><p className="text-xs font-semibold text-muted">Total headcount</p><p className="mt-2 font-mono text-2xl font-bold text-ink">486</p><p className="mt-1 text-xs text-cta">+12 this month</p></div><div className="card"><p className="text-xs font-semibold text-muted">Reporting layers</p><p className="mt-2 font-mono text-2xl font-bold text-ink">4</p><p className="mt-1 text-xs text-muted">From CEO to individual contributor</p></div><div className="card"><p className="text-xs font-semibold text-muted">Open positions</p><p className="mt-2 font-mono text-2xl font-bold text-ink">12</p><p className="mt-1 text-xs text-primary">Across 6 departments</p></div></div>
    {selectedTeam && <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><div className="absolute inset-0 bg-ink/40" onClick={() => setSelectedTeam(null)} /><div className="relative w-full max-w-sm rounded-2xl bg-canvas border border-hairline shadow-2xl p-6"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className={`w-11 h-11 rounded-full flex items-center justify-center ${selectedTeam.color}`}><span className="text-sm font-bold">{selectedTeam.initials}</span></div><div><h2 className="text-base font-bold text-ink">{selectedTeam.name}</h2><p className="text-xs text-muted mt-0.5">{selectedTeam.description}</p></div></div><button onClick={() => setSelectedTeam(null)} aria-label="Close team details" className="btn-secondary min-h-10 min-w-10 px-3"><X size={15} /></button></div><div className="mt-5 space-y-3 border-t border-hairline-soft pt-4"><div className="flex justify-between text-sm"><span className="text-muted">Department head</span><span className="font-semibold text-ink">{selectedTeam.lead}</span></div><div className="flex justify-between text-sm"><span className="text-muted">Team members</span><span className="font-mono font-semibold text-ink">{selectedTeam.count}</span></div><div className="flex justify-between text-sm"><span className="text-muted">Open roles</span><span className="font-mono font-semibold text-primary">{selectedTeam.children?.length || 2}</span></div></div><button onClick={() => setSelectedTeam(null)} className="btn-cta w-full mt-5 text-sm">View department</button></div></div>}
  </div>;
}
