'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, Mail, Phone, MapPin, Calendar, Building2, Briefcase, Pencil, MoreHorizontal, FileText, Wallet, CalendarDays, Clock, Download, Eye, X, CheckCircle2 } from 'lucide-react';
import { useToast } from '@/components/ui/Toast';

const emp = {
  id: '1', employeeId: 'EMP-20260101-001', name: 'Rina Sari', email: 'rina.sari@company.com', phone: '+628123456789',
  nik: '3201234567890001', npwp: '12.345.678.9-012.000', joinDate: '2020-03-15', department: 'Human Resources',
  position: 'HR Manager', status: 'active', address: 'Jl. Sudirman No. 123, Jakarta Selatan',
  emergencyContact: 'Budi Sari — +628987654321 (Spouse)', salary: 15000000, bank: 'BCA — 1234567890',
};

const documents = [
  { name: 'Employment contract', type: 'Contract', uploaded: '15 Mar 2020', status: 'Valid' },
  { name: 'KTP / Identity card', type: 'Identity', uploaded: '15 Mar 2020', status: 'Valid' },
  { name: 'NPWP document', type: 'Tax', uploaded: '16 Mar 2020', status: 'Valid' },
  { name: 'BPJS registration', type: 'Benefits', uploaded: '20 Mar 2020', status: 'Valid' },
];
const payroll = [
  { month: 'September 2026', gross: 16500000, deductions: 3105000, net: 13395000, status: 'Paid' },
  { month: 'August 2026', gross: 16500000, deductions: 3105000, net: 13395000, status: 'Paid' },
  { month: 'July 2026', gross: 16500000, deductions: 3105000, net: 13395000, status: 'Paid' },
  { month: 'June 2026', gross: 16500000, deductions: 3105000, net: 13395000, status: 'Paid' },
];
const leave = [
  { type: 'Annual Leave', dates: '12–14 Aug 2026', days: 3, status: 'Approved' },
  { type: 'Sick Leave', dates: '03 Jun 2026', days: 1, status: 'Approved' },
  { type: 'Annual Leave', dates: '20–21 Apr 2026', days: 2, status: 'Approved' },
];
function rupiah(n: number) { return `Rp ${n.toLocaleString('id-ID')}`; }

type Tab = 'Overview' | 'Documents' | 'Payroll' | 'Leave' | 'Attendance';

export default function EmployeeDetailPage() {
  const [tab, setTab] = useState<Tab>('Overview');
  const [showEdit, setShowEdit] = useState(false);
  const { toast } = useToast();
  return <div>
    <Link href="/employees" className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:text-primary-hover transition-colors mb-5"><ArrowLeft size={14} /> Back to Employees</Link>
    <div className="flex flex-col sm:flex-row sm:items-start gap-4 sm:gap-5 mb-6"><div className="w-16 h-16 rounded-2xl bg-primary-surface flex items-center justify-center shrink-0"><span className="text-xl font-bold text-primary">RS</span></div><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold text-ink tracking-tight">{emp.name}</h1><span className="badge bg-cta-surface text-cta-hover capitalize">{emp.status}</span></div><p className="text-sm text-muted mt-1 font-mono">{emp.employeeId}</p><div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-3 text-sm text-body"><span className="flex items-center gap-1.5"><Briefcase size={14} className="text-muted" /> {emp.position}</span><span className="flex items-center gap-1.5"><Building2 size={14} className="text-muted" /> {emp.department}</span><span className="flex items-center gap-1.5"><Calendar size={14} className="text-muted" /> Joined {new Date(emp.joinDate).toLocaleDateString('id-ID', { month: 'long', year: 'numeric' })}</span></div></div><div className="flex gap-2"><button onClick={() => setShowEdit(true)} className="btn-secondary gap-2"><Pencil size={14} /> Edit Profile</button><button className="btn-secondary min-w-11 px-3" aria-label="More actions"><MoreHorizontal size={16} /></button></div></div>
    <div className="flex gap-1 overflow-x-auto border-b border-hairline mb-6" role="tablist">{(['Overview', 'Documents', 'Payroll', 'Leave', 'Attendance'] as Tab[]).map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`min-h-11 px-4 text-sm font-semibold whitespace-nowrap border-b-2 transition-colors ${tab === item ? 'border-primary text-primary' : 'border-transparent text-muted hover:text-ink'}`}>{item}</button>)}</div>
    {tab === 'Overview' && <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><InfoCard title="Personal Details"><Row label="NIK" value={emp.nik} mono /><Row label="NPWP" value={emp.npwp} mono /><Row label="Email" value={emp.email} icon={<Mail size={13} />} /><Row label="Phone" value={emp.phone} icon={<Phone size={13} />} /><div className="pt-3 border-t border-hairline-soft"><span className="text-muted text-xs flex items-center gap-1.5"><MapPin size={13} /> Address</span><p className="text-ink mt-1.5 text-sm">{emp.address}</p></div><div className="pt-3 border-t border-hairline-soft"><span className="text-muted text-xs">Emergency Contact</span><p className="text-ink mt-1.5 text-sm">{emp.emergencyContact}</p></div></InfoCard><InfoCard title="Employment"><Row label="Department" value={emp.department} /><Row label="Position" value={emp.position} /><Row label="Status" value="Active" /><Row label="Join Date" value={new Date(emp.joinDate).toLocaleDateString('id-ID')} /><div className="mt-4 rounded-xl bg-primary-surface p-4"><p className="text-xs text-primary font-semibold">Tenure</p><p className="text-xl font-mono font-bold text-ink mt-1">6 years</p><p className="text-[11px] text-muted mt-1">Since March 2020</p></div></InfoCard><InfoCard title="Compensation"><Row label="Base Salary" value={rupiah(emp.salary)} mono /><Row label="Monthly gross" value={rupiah(16500000)} mono /><Row label="Bank" value={emp.bank} /><div className="mt-4 rounded-xl bg-cta-surface p-4"><p className="text-xs text-cta font-semibold">Leave balance</p><p className="text-xl font-mono font-bold text-ink mt-1">9 days</p><p className="text-[11px] text-muted mt-1">of 12 annual days remaining</p></div></InfoCard></div>}
    {tab === 'Documents' && <DataCard title="Employee documents" description="Personal and employment documents" icon={FileText}><div className="space-y-2">{documents.map((doc) => <div key={doc.name} className="flex items-center gap-3 p-3 rounded-xl border border-hairline hover:bg-surface-soft transition-colors"><div className="w-9 h-9 rounded-lg bg-primary-surface flex items-center justify-center"><FileText size={15} className="text-primary" /></div><div className="flex-1"><p className="text-sm font-semibold text-ink">{doc.name}</p><p className="text-[11px] text-muted">{doc.type} · Uploaded {doc.uploaded}</p></div><span className="badge bg-cta-surface text-cta text-[10px]">{doc.status}</span><button aria-label={`Preview ${doc.name}`} className="min-h-9 min-w-9 rounded-lg hover:bg-primary-surface flex items-center justify-center"><Eye size={14} className="text-primary" /></button><button aria-label={`Download ${doc.name}`} className="min-h-9 min-w-9 rounded-lg hover:bg-primary-surface flex items-center justify-center"><Download size={14} className="text-muted" /></button></div>)}</div></DataCard>}
    {tab === 'Payroll' && <DataCard title="Payroll history" description="Monthly payslips and compensation breakdown" icon={Wallet}><SimpleTable headers={['Month', 'Gross', 'Deductions', 'Net pay', 'Status']} rows={payroll.map((row) => [row.month, rupiah(row.gross), rupiah(row.deductions), rupiah(row.net), row.status])} /></DataCard>}
    {tab === 'Leave' && <DataCard title="Leave history" description="Approved and past leave requests" icon={CalendarDays}><SimpleTable headers={['Leave type', 'Dates', 'Days', 'Status']} rows={leave.map((row) => [row.type, row.dates, `${row.days} day${row.days > 1 ? 's' : ''}`, row.status])} /></DataCard>}
    {tab === 'Attendance' && <DataCard title="Attendance summary" description="Current month attendance overview" icon={Clock}><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5"><Metric label="Present days" value="18" /><Metric label="Late arrivals" value="1" /><Metric label="Attendance rate" value="94.7%" /></div><div className="rounded-xl border border-hairline p-4 flex items-center gap-3"><CheckCircle2 size={18} className="text-cta" /><div><p className="text-sm font-semibold text-ink">Good attendance standing</p><p className="text-xs text-muted mt-0.5">No attendance issues requiring attention.</p></div></div></DataCard>}
    {showEdit && <EditModal onClose={() => setShowEdit(false)} onSave={() => { setShowEdit(false); toast('Employee profile updated successfully.', 'success'); }} />}
  </div>;
}

function InfoCard({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card space-y-4"><h2 className="text-sm font-bold text-ink">{title}</h2><div className="space-y-3">{children}</div></div>; }
function Row({ label, value, mono = false, icon }: { label: string; value: string; mono?: boolean; icon?: React.ReactNode }) { return <div className="flex justify-between gap-4 text-sm"><span className="text-muted flex items-center gap-1.5">{icon}{label}</span><span className={`${mono ? 'font-mono' : ''} text-ink text-right break-all`}>{value}</span></div>; }
function DataCard({ title, description, icon: Icon, children }: { title: string; description: string; icon: typeof FileText; children: React.ReactNode }) { return <div className="card"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-lg bg-primary-surface flex items-center justify-center"><Icon size={17} className="text-primary" /></div><div><h2 className="text-sm font-bold text-ink">{title}</h2><p className="text-xs text-muted mt-0.5">{description}</p></div></div>{children}</div>; }
function SimpleTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[620px]"><thead><tr className="border-b border-hairline">{headers.map((header) => <th key={header} className="table-header">{header}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="table-row">{row.map((cell, j) => <td key={j} className={`table-cell ${j > 0 ? 'text-body' : 'font-semibold text-ink'}`}>{j === row.length - 1 ? <span className="badge bg-cta-surface text-cta text-[10px]">{cell}</span> : cell}</td>)}</tr>)}</tbody></table></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-surface-soft p-4"><p className="text-xs text-muted">{label}</p><p className="text-xl font-mono font-bold text-ink mt-1">{value}</p></div>; }
function EditModal({ onClose, onSave }: { onClose: () => void; onSave: () => void }) { return <div className="fixed inset-0 z-[80] flex items-center justify-center p-4" role="dialog" aria-modal="true"><div className="absolute inset-0 bg-ink/40" onClick={onClose} /><div className="relative w-full max-w-md rounded-2xl bg-canvas border border-hairline shadow-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-bold text-ink">Edit employee profile</h2><p className="text-xs text-muted mt-1">Update contact and employment details</p></div><button onClick={onClose} aria-label="Close" className="btn-secondary min-h-10 min-w-10 px-3"><X size={15} /></button></div><div className="space-y-4"><label className="block text-sm font-semibold text-ink">Email<input defaultValue={emp.email} type="email" className="input-field mt-1.5" /></label><label className="block text-sm font-semibold text-ink">Phone<input defaultValue={emp.phone} className="input-field mt-1.5" /></label><label className="block text-sm font-semibold text-ink">Address<textarea defaultValue={emp.address} rows={2} className="input-field mt-1.5" /></label></div><div className="flex justify-end gap-3 mt-6 pt-4 border-t border-hairline-soft"><button onClick={onClose} className="btn-secondary text-sm">Cancel</button><button onClick={onSave} className="btn-cta text-sm">Save changes</button></div></div></div>; }
