import { NextResponse } from 'next/server';
import { apiError, getSupabaseAdmin, requireAdmin, requireUser } from '@/lib/server/auth';

function selectQuery(client: ReturnType<typeof getSupabaseAdmin>, id: string) { return client.from('expense_claims').select('*, employee:employee_id(full_name,departments(name)), reviewer:reviewed_by(email)').eq('id', id); }
function normalize(row: any) { const employee = row.employee ?? {}; const department = Array.isArray(employee.departments) ? employee.departments[0] : employee.departments; return { ...row, amount: Number(row.amount), employee: employee.full_name ?? 'Unknown employee', department: department?.name ?? 'Unassigned', initials: (employee.full_name ?? 'U').split(/\s+/).map((x: string) => x[0]).join('').slice(0, 2).toUpperCase(), receipt_attached: row.receipt_attached, submitted_date: row.submitted_at, reviewed_by: row.reviewer?.email ?? null }; }

export async function GET(request: Request, { params }: { params: { id: string } }) { try { const user = await requireUser(request); const client = getSupabaseAdmin(); let query = selectQuery(client, params.id); if (!['super_admin', 'hr_director', 'hr_manager', 'hr_officer'].includes(user.role)) { if (!user.employee_id) return NextResponse.json({ detail: 'Your user account is not linked to an employee record' }, { status: 422 }); query = query.eq('employee_id', user.employee_id); } const { data, error } = await query.maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ detail: 'Expense claim not found' }, { status: 404 }); return NextResponse.json(normalize(data)); } catch (error) { return apiError(error); } }

export async function PUT(request: Request, { params }: { params: { id: string } }) { try { const user = await requireUser(request); requireAdmin(user); const body = await request.json(); const update: Record<string, unknown> = {}; for (const key of ['category', 'description', 'expense_date', 'amount']) if (body[key] !== undefined) update[key] = key === 'amount' ? Number(body[key]) : String(body[key]).trim(); if (update.amount !== undefined && (!Number.isFinite(update.amount) || Number(update.amount) <= 0)) return NextResponse.json({ detail: 'Amount must be positive' }, { status: 422 }); update.updated_at = new Date().toISOString(); const client = getSupabaseAdmin(); const { data, error } = await client.from('expense_claims').update(update).eq('id', params.id).eq('status', 'pending').select('*, employee:employee_id(full_name,departments(name)), reviewer:reviewed_by(email)').maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ detail: 'Only pending claims can be edited' }, { status: 409 }); return NextResponse.json(normalize(data)); } catch (error) { return apiError(error); } }

export async function DELETE(request: Request, { params }: { params: { id: string } }) { try { const user = await requireUser(request); const client = getSupabaseAdmin(); let query = client.from('expense_claims').delete().eq('id', params.id).eq('status', 'pending'); if (!['super_admin', 'hr_director', 'hr_manager', 'hr_officer'].includes(user.role)) { if (!user.employee_id) return NextResponse.json({ detail: 'Your user account is not linked to an employee record' }, { status: 422 }); query = query.eq('employee_id', user.employee_id); } const { data, error } = await query.select('id').maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ detail: 'Only your pending claims can be deleted' }, { status: 409 }); await client.from('audit_logs').insert({ user_id: user.id, entity_type: 'expense_claim', entity_id: params.id, action: 'delete' }); return new NextResponse(null, { status: 204 }); } catch (error) { return apiError(error); } }
