import { NextResponse } from 'next/server';
import { apiError, getSupabaseAdmin, requirePermission, requireUser } from '@/lib/server/auth';
import { orIlike } from '@/lib/server/query';

const TYPES = ['Contract', 'Identity', 'Tax', 'Benefits', 'Legal', 'Medical'];
function statusFor(expiry: string | null) { if (!expiry) return 'valid'; const days = (new Date(`${expiry}T00:00:00`).getTime() - Date.now()) / 86400000; return days < 0 ? 'expired' : days <= 30 ? 'expiring' : 'valid'; }
function normalize(row: any) { const employee = Array.isArray(row.employee) ? row.employee[0] : row.employee; const uploader = Array.isArray(row.uploader) ? row.uploader[0] : row.uploader; const expiry = row.expiry_date ?? null; return { id: row.id, name: row.name, employee: employee?.full_name ?? 'Unknown employee', employee_id: row.employee_id, type: row.document_type, size_bytes: Number(row.size_bytes), size: Number(row.size_bytes) >= 1048576 ? `${(Number(row.size_bytes) / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.round(Number(row.size_bytes) / 1024))} KB`, uploaded: new Date(row.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), expiry: expiry ? new Date(`${expiry}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—', expiry_date: expiry, status: statusFor(expiry), uploadBy: uploader?.email ?? 'System', reminderSent: Boolean(row.reminder_sent_at), renewalRequested: Boolean(row.renewal_requested_at), mime_type: row.mime_type, original_filename: row.original_filename, download_url: row.download_url ?? null }; }
async function withUrls(rows: any[], client: ReturnType<typeof getSupabaseAdmin>) { return Promise.all(rows.map(async row => { if (row.storage_path) { const signed = await client.storage.from('documents').createSignedUrl(row.storage_path, 300); row.download_url = signed.data?.signedUrl ?? null; } return normalize(row); })); }

export async function GET(request: Request) { try { const user = await requireUser(request); const elevated = ['super_admin', 'hr_director', 'hr_manager', 'hr_officer'].includes(user.role); const { searchParams } = new URL(request.url); const search = searchParams.get('search')?.trim(); const type = searchParams.get('type'); const client = getSupabaseAdmin(); let query = client.from('documents').select('*, employee:employee_id(full_name), uploader:uploaded_by(email)', { count: 'exact' }).eq('organization_id', user.organization_id); if (!elevated) { if (!user.employee_id) return NextResponse.json({ detail: 'Your user account is not linked to an employee record' }, { status: 422 }); query = query.eq('employee_id', user.employee_id); } if (search) query = query.or(orIlike(search, ['name', 'document_type'])); if (type && type !== 'All Documents') query = query.eq('document_type', type); const { data, count, error } = await query.order('created_at', { ascending: false }); if (error) throw error; return NextResponse.json({ items: await withUrls(data ?? [], client), total: count ?? 0 }); } catch (error) { return apiError(error); } }

export async function POST(request: Request) { try { const user = await requireUser(request); requirePermission(user, 'documents:write'); const form = await request.formData(); const file = form.get('file'); const type = String(form.get('document_type') ?? 'Contract'); const employeeName = String(form.get('employee') ?? '').trim(); const expiry = String(form.get('expiry_date') ?? '').trim() || null; if (!(file instanceof File) || file.size === 0) return NextResponse.json({ detail: 'A document file is required' }, { status: 422 }); if (file.size > 10 * 1024 * 1024) return NextResponse.json({ detail: 'File must be 10 MB or smaller' }, { status: 422 }); if (!TYPES.includes(type)) return NextResponse.json({ detail: 'Invalid document type' }, { status: 422 }); const client = getSupabaseAdmin(); let employeeQuery = client.from('employees').select('id,full_name').eq('status', 'active'); if (employeeName) employeeQuery = employeeQuery.eq('full_name', employeeName); const { data: employee } = await employeeQuery.limit(1).maybeSingle(); if (!employee) return NextResponse.json({ detail: 'Active employee not found' }, { status: 404 }); const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `${employee.id}/${crypto.randomUUID()}-${safeName}`; const upload = await client.storage.from('documents').upload(path, file, { contentType: file.type || 'application/octet-stream', upsert: false }); if (upload.error) throw upload.error; const { data, error } = await client.from('documents').insert({ organization_id: user.organization_id, employee_id: employee.id, name: file.name.replace(/\.[^.]+$/, ''), document_type: type, original_filename: file.name, storage_path: path, mime_type: file.type || null, size_bytes: file.size, expiry_date: expiry, status: statusFor(expiry), uploaded_by: user.id }).select('*, employee:employee_id(full_name), uploader:uploaded_by(email)').single(); if (error) { await client.storage.from('documents').remove([path]); throw error; } await client.from('audit_logs').insert({ organization_id: user.organization_id, user_id: user.id, entity_type: 'document', entity_id: data.id, action: 'create', new_value: file.name }); return NextResponse.json(normalize(data), { status: 201 }); } catch (error) { return apiError(error); } }
