import { NextResponse } from 'next/server';
import { apiError, getSupabaseAdmin, requireAdmin, requireUser } from '@/lib/server/auth';

const templates = [
  ['welcome', 'Send welcome email', 'HR'], ['documents', 'Collect employment documents', 'HR'], ['account', 'Create email & system accounts', 'IT'], ['equipment', 'Prepare laptop and equipment', 'IT'], ['policies', 'Review company policies', 'HR'], ['intro', 'Schedule company introduction', 'HR'], ['manager', 'Manager 1:1 meeting', 'Manager'], ['team', 'Team introduction', 'Manager'], ['buddy', 'Assign onboarding buddy', 'HR'], ['goals', 'Set first 30-day goals', 'Manager'], ['training', 'Complete security training', 'IT'], ['feedback', '30-day check-in', 'Manager'],
] as const;
function initials(name: string) { return name.split(/\s+/).map(x => x[0]).join('').slice(0, 2).toUpperCase(); }
function normalize(row: any) { const tasks = Array.isArray(row.tasks) ? row.tasks : []; const done = tasks.filter((t: any) => t.done).length; return { id: row.id, name: row.name, role: row.role, department: row.department, start: new Date(`${row.start_date}T00:00:00`).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), start_date: row.start_date, status: row.status, initials: initials(row.name), buddy: row.buddy, tasks: tasks.map((t: any) => ({ id: t.task_key, label: t.label, owner: t.owner, due: new Date(`${t.due_date}T00:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }), due_date: t.due_date, done: t.done, overdue: !t.done && new Date(t.due_date) < new Date() })), progress: tasks.length ? Math.round(done / tasks.length * 100) : 0 }; }
async function fetchRecords(client: ReturnType<typeof getSupabaseAdmin>, id?: string, organizationId?: string) { let query = client.from('onboarding_records').select('*, tasks:onboarding_tasks(*)'); if (organizationId) query = query.eq('organization_id', organizationId); if (id) query = query.eq('id', id); const result = await query.order('created_at', { ascending: false }); if (result.error) throw result.error; return result.data ?? []; }
export async function GET(request: Request) { try { const user = await requireUser(request); requireAdmin(user); const client = getSupabaseAdmin(); return NextResponse.json({ items: (await fetchRecords(client)).filter((r: any) => r.organization_id === user.organization_id).map(normalize) }); } catch (error) { return apiError(error); } }
export async function POST(request: Request) { try { const user = await requireUser(request); requireAdmin(user); const body = await request.json(); const name = String(body.name ?? '').trim(); const role = String(body.role ?? '').trim(); const department = String(body.department ?? '').trim(); const startDate = String(body.start_date ?? '').trim(); if (!name || !role || !department || !/^\d{4}-\d{2}-\d{2}$/.test(startDate)) return NextResponse.json({ detail: 'Name, role, department, and valid start date are required' }, { status: 422 }); const client = getSupabaseAdmin(); const { data: record, error } = await client.from('onboarding_records').insert({ organization_id: user.organization_id, name, role, department, start_date: startDate, buddy: String(body.buddy ?? 'Not assigned') }).select().single(); if (error) throw error; const taskRows = templates.map(([task_key, label, owner], index) => ({ onboarding_id: record.id, task_key, label, owner, due_date: new Date(new Date(`${startDate}T00:00:00`).getTime() + index * 86400000).toISOString().slice(0, 10) })); const taskInsert = await client.from('onboarding_tasks').insert(taskRows); if (taskInsert.error) throw taskInsert.error; await client.from('audit_logs').insert({ user_id: user.id, entity_type: 'onboarding', entity_id: record.id, action: 'create', new_value: name }); return NextResponse.json(normalize((await fetchRecords(client, record.id, user.organization_id))[0]), { status: 201 }); } catch (error) { return apiError(error); } }
