'use client';

import { useEffect, useMemo, useState } from 'react';
import { Users, Clock, AlertTriangle, CheckCircle2, Search, X, ChevronLeft, ChevronRight, UserPlus, FileText } from 'lucide-react';
import ModuleHeader from '@/components/ui/ModuleHeader';
import StatCard from '@/components/ui/StatCard';
import EmptyState from '@/components/ui/EmptyState';
import ConfirmDialog from '@/components/ui/ConfirmDialog';
import { useToast } from '@/components/ui/Toast';
import api from '@/lib/api';

type AttendanceStatus = 'present' | 'late' | 'absent' | 'half-day' | 'leave' | 'wfh';
type AttendanceRecord = { id: string; employee_id: string; name: string; initials: string; department: string; check_in_time: string | null; check_out_time: string | null; status: AttendanceStatus; hours: string; date: string; };
type Employee = { id: string; full_name: string; department?: string | null };
type CurrentUser = { role: string; employee_id: string | null };
const statusMeta: Record<AttendanceStatus, { label: string; color: string }> = { present: { label: 'Present', color: 'bg-cta-surface text-cta-hover' }, late: { label: 'Late', color: 'bg-amber-50 text-accent-yellow' }, absent: { label: 'Absent', color: 'bg-red-50 text-semantic-down' }, 'half-day': { label: 'Half Day', color: 'bg-primary-surface text-primary' }, leave: { label: 'On Leave', color: 'bg-surface-strong text-muted' }, wfh: { label: 'WFH', color: 'bg-sky-50 text-sky-600' } };
function dateKey(date: Date) { return date.toISOString().slice(0, 10); }
function generateWeekDates(offset: number) { const today = new Date(); const monday = new Date(today); monday.setDate(today.getDate() - ((today.getDay() + 6) % 7) + offset * 7); return ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((short, i) => { const d = new Date(monday); d.setDate(monday.getDate() + i); return { short, key: dateKey(d), label: d.toLocaleDateString('id-ID', { day: 'numeric', month: 'short' }), isToday: d.toDateString() === today.toDateString() }; }); }

export default function AttendancePage() {
  const [search, setSearch] = useState(''); const [weekOffset, setWeekOffset] = useState(0); const [selectedDay, setSelectedDay] = useState(() => Math.min(4, (new Date().getDay() + 6) % 7));
  const [records, setRecords] = useState<AttendanceRecord[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [currentUser, setCurrentUser] = useState<CurrentUser | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [showManualEntry, setShowManualEntry] = useState(false); const [clockedIn, setClockedIn] = useState<AttendanceRecord | null>(null); const [confirmClockOut, setConfirmClockOut] = useState(false); const [saving, setSaving] = useState(false); const { toast } = useToast();
  const weekDates = useMemo(() => generateWeekDates(weekOffset), [weekOffset]); const selectedDate = weekDates[selectedDay]?.key ?? dateKey(new Date());
  const load = async () => { setLoading(true); setError(''); try { const [attendance, employeeResponse, me] = await Promise.all([api.get('/attendance', { params: { date: selectedDate, search, per_page: 100 } }), api.get('/employees', { params: { status: 'active', per_page: 100 } }), api.get('/auth/me')]); setRecords(attendance.data.items); setEmployees(employeeResponse.data.items); setCurrentUser(me.data); const own = attendance.data.items.find((r: AttendanceRecord) => r.employee_id === me.data.employee_id && r.check_in_time && !r.check_out_time); setClockedIn(own ?? null); } catch (e: any) { setError(e.response?.data?.detail || 'Could not load attendance data.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [selectedDate]);
  const filtered = records.filter((row) => row.name.toLowerCase().includes(search.toLowerCase())); const presentCount = filtered.filter((r) => r.status === 'present' || r.status === 'wfh').length; const lateCount = filtered.filter((r) => r.status === 'late').length; const absentCount = filtered.filter((r) => r.status === 'absent' || r.status === 'leave').length;
  const handleClockIn = async () => { if (!currentUser?.employee_id) return toast('Your account is not linked to an employee.', 'error'); setSaving(true); try { const response = await api.post('/attendance', { employee_id: currentUser.employee_id, date: selectedDate, status: 'present', check_in_time: new Date().toTimeString().slice(0, 5) }); setClockedIn(response.data); await load(); toast('Clock in recorded.', 'success'); } catch (e: any) { toast(e.response?.data?.detail || 'Could not clock in.', 'error'); } finally { setSaving(false); } };
  const handleClockOut = async () => { if (!clockedIn) return; setSaving(true); try { await api.put(`/attendance/${clockedIn.id}`, { check_out_time: new Date().toTimeString().slice(0, 5) }); setConfirmClockOut(false); setClockedIn(null); await load(); toast('Clock out recorded. Hours worked calculated automatically.', 'success'); } catch (e: any) { toast(e.response?.data?.detail || 'Could not clock out.', 'error'); } finally { setSaving(false); } };
  const submitManualEntry = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await api.post('/attendance', { employee_id: String(form.get('employee')), date: String(form.get('date')), check_in_time: String(form.get('checkIn')), check_out_time: String(form.get('checkOut') || ''), status: String(form.get('status') || 'present'), notes: String(form.get('reason') || ''), source: 'manual' }); setShowManualEntry(false); await load(); toast('Attendance record added.', 'success'); } catch (e: any) { toast(e.response?.data?.detail || 'Could not save attendance.', 'error'); } finally { setSaving(false); } };

  return <div>
    <ModuleHeader eyebrow="Time & attendance" title="Attendance" description="Track daily attendance, punctuality, and team hours" action={<div className="flex gap-2"><button onClick={() => setShowManualEntry(true)} className="btn-secondary gap-2"><UserPlus size={15} /> Manual entry</button>{clockedIn ? <button onClick={() => setConfirmClockOut(true)} disabled={saving} className="btn-cta gap-2 bg-semantic-down hover:bg-semantic-down/90 text-white border-semantic-down"><Clock size={15} /> Clock out</button> : <button onClick={() => void handleClockIn()} disabled={saving} className="btn-cta gap-2 disabled:opacity-50"><Clock size={15} /> Clock in</button>}</div>} />
    {error && <div className="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 flex items-center justify-between"><p className="text-sm text-semantic-down">{error}</p><button onClick={() => void load()} className="btn-secondary text-xs">Retry</button></div>}
    {clockedIn && <div className="rounded-xl border border-cta/30 bg-cta-surface p-4 mb-6 flex items-center gap-4"><Clock size={20} className="text-cta" /><div className="flex-1"><p className="text-sm font-bold text-ink">You are clocked in</p><p className="text-xs text-muted">Checked in at {clockedIn.check_in_time} · Working time in progress</p></div><span className="font-mono text-lg font-bold text-cta">Active</span></div>}
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6"><StatCard icon={CheckCircle2} label="Present" value={loading ? '—' : String(presentCount)} tone="green" detail={`${filtered.length ? ((presentCount / filtered.length) * 100).toFixed(1) : '0.0'}% attendance rate`} /><StatCard icon={AlertTriangle} label="Late" value={loading ? '—' : String(lateCount)} tone="amber" detail="Of team" /><StatCard icon={Clock} label="Average hours" value={loading ? '—' : 'Live'} tone="primary" detail="Selected day" /><StatCard icon={Users} label="Absent" value={loading ? '—' : String(absentCount)} tone="red" detail="Includes leave + no-show" /></div>
    <div className="card mb-6"><div className="flex items-center justify-between mb-3"><button onClick={() => { setWeekOffset((w) => w - 1); setSelectedDay(0); }} className="min-h-10 min-w-10 rounded-md hover:bg-primary-surface" aria-label="Previous week"><ChevronLeft size={16} className="text-muted mx-auto" /></button><h2 className="text-sm font-bold text-ink">{weekOffset === 0 ? 'This week' : weekOffset < 0 ? `${Math.abs(weekOffset)} week(s) ago` : `${weekOffset} week(s) ahead`}</h2><button onClick={() => { setWeekOffset((w) => w + 1); setSelectedDay(0); }} className="min-h-10 min-w-10 rounded-md hover:bg-primary-surface" aria-label="Next week"><ChevronRight size={16} className="text-muted mx-auto" /></button></div><div className="flex gap-3 overflow-x-auto pb-2">{weekDates.map((day, i) => <button key={day.key} onClick={() => setSelectedDay(i)} className={`flex-1 min-w-[80px] rounded-lg border p-3 text-center ${i === selectedDay ? 'border-primary bg-primary-surface' : 'border-hairline bg-canvas hover:border-primary-light'}`}><p className={`text-[11px] font-semibold uppercase ${i === selectedDay ? 'text-primary' : 'text-muted'}`}>{day.short}</p><p className="text-xs mt-1 text-body">{day.label}</p>{day.isToday && <span className="inline-block mt-1.5 px-2 py-0.5 rounded-pill bg-primary text-white text-[9px] font-bold">TODAY</span>}</button>)}</div></div>
    <div className="card p-0 overflow-hidden"><div className="px-5 py-4 border-b border-hairline-soft flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="relative max-w-xs flex-1"><Search size={14} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-soft" /><input type="search" aria-label="Search attendance" placeholder="Search by name..." value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void load()} className="w-full min-h-10 rounded-pill bg-surface-strong pl-9 pr-3 py-2 text-sm text-ink" /></div><p className="text-xs text-muted">{loading ? 'Loading…' : `${filtered.length} records`}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px]"><thead><tr className="border-b border-hairline"><th className="table-header">Employee</th><th className="table-header">Department</th><th className="table-header">Check In</th><th className="table-header">Check Out</th><th className="table-header">Hours</th><th className="table-header">Status</th></tr></thead><tbody>{!loading && filtered.length === 0 ? <tr><td colSpan={6}><EmptyState title="No attendance records found" description="Create a manual entry or choose another date." /></td></tr> : filtered.map((row) => <tr key={row.id} className="table-row"><td className="table-cell"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-primary-surface flex items-center justify-center"><span className="text-[11px] font-bold text-primary">{row.initials}</span></div><span className="font-semibold text-ink">{row.name}</span></div></td><td className="table-cell text-body">{row.department}</td><td className="table-cell font-mono text-xs text-ink">{row.check_in_time ?? '—'}</td><td className="table-cell font-mono text-xs text-ink">{row.check_out_time ?? '—'}</td><td className="table-cell font-mono text-xs text-ink">{row.hours}</td><td className="table-cell"><span className={`badge capitalize ${statusMeta[row.status]?.color}`}>{statusMeta[row.status]?.label}</span></td></tr>)}</tbody></table></div><div className="px-5 py-4 border-t border-hairline-soft"><p className="text-xs text-muted">Showing {filtered.length} records for {selectedDate}</p></div></div>
    <ConfirmDialog open={confirmClockOut} title="Clock out now?" description="Your working hours will be calculated from your clock-in time." confirmLabel="Clock out" onConfirm={() => void handleClockOut()} onCancel={() => setConfirmClockOut(false)} />
    {showManualEntry && <div className="fixed inset-0 z-[80] flex items-center justify-center p-4"><div className="absolute inset-0 bg-ink/40" onClick={() => setShowManualEntry(false)} /><form onSubmit={submitManualEntry} className="relative w-full max-w-md rounded-2xl bg-canvas border border-hairline shadow-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-bold text-ink">Manual attendance entry</h2><p className="text-xs text-muted mt-1">For cases where system check-in fails</p></div><button type="button" onClick={() => setShowManualEntry(false)} aria-label="Close manual entry form" className="btn-secondary min-h-10 min-w-10 px-3"><X size={15} /></button></div><div className="space-y-4"><label className="block text-sm font-semibold text-ink">Employee<select name="employee" required className="input-field mt-1.5"><option value="">Select employee...</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.full_name}</option>)}</select></label><label className="block text-sm font-semibold text-ink">Date<input name="date" type="date" defaultValue={selectedDate} required className="input-field mt-1.5" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-semibold text-ink">Check-in<input name="checkIn" type="time" required className="input-field mt-1.5" /></label><label className="block text-sm font-semibold text-ink">Check-out<input name="checkOut" type="time" className="input-field mt-1.5" /></label></div><label className="block text-sm font-semibold text-ink">Status<select name="status" className="input-field mt-1.5">{Object.entries(statusMeta).map(([value, meta]) => <option key={value} value={value}>{meta.label}</option>)}</select></label><label className="block text-sm font-semibold text-ink">Reason<textarea name="reason" rows={2} required className="input-field mt-1.5" /></label></div><div className="flex justify-end gap-3 mt-6 pt-4 border-t border-hairline-soft"><button type="button" onClick={() => setShowManualEntry(false)} className="btn-secondary text-sm">Cancel</button><button type="submit" disabled={saving} className="btn-cta text-sm gap-2 disabled:opacity-50"><FileText size={14} /> Submit entry</button></div></form></div>}
  </div>;
}
